### PR TITLE
Remove manual steps to install static assets (fonts), and automate th…

### PR DESCRIPTION
**Pull request by hostep**
…e install using magento/magento-composer-installer

This PR
- removes the manual installation steps and script to copy font files in your Magento installation
- introduces the `magento/magento-composer-installer` dependency which can automate the install of font files in your Magento installation

This is a little-known feature in Magento, but you can see that Magento's `magento/magento2-base` module uses the same feature to copy files from it, to your Magento install.
The difference is that `magento/magento2-base` is of `type` `magento2-component`, while this module is of `type` `magento2-module`. The `type` determines the location where files are copied to as described in [the documentation](https://github.com/magento/magento-composer-installer/#supported-components). So I needed to prepend the path with `../../` so it would install the fonts in `{root-magento-project}/lib` and not `{root-magento-project}/app/code/lib/`

To test:
1. Add the following to the `repositories` section of the  `composer.json` file of a Magento installation:
```json
        {
            "type": "vcs",
            "url": "https://github.com/baldwin-agency/koongo-magento2-data-feed-manager"
        }
```
2. Verify that `lib/web/fonts/` does **not** has a directory `Nostress_Koongo` with the fonts from this module
3. Execute:
```
composer require koongo-com/magento2-data-feed-manager:dev-automate-install-of-custom-fonts
```
4. Verify that `lib/web/fonts/` **does** have a directory `Nostress_Koongo` with the fonts from this module and that in the Magento backoffice the font is loaded correctly
5. Execute:
```
composer remove koongo-com/magento2-data-feed-manager
```
6. Verify that `lib/web/fonts/` does **not** has a directory `Nostress_Koongo` with the fonts from this module

### CODE REVIEW

**Comment by hostep** [comment]
@pecinaon: if you have a little time, I would appreciate it if you could review this a bit, thanks! 🙂

**Comment by hostep** [comment]
Hey @pecinaon: what are your thoughts on this? Thanks!

**Comment by hostep** [comment]
Hey @pecinaon or @tomasfriedrich, have you guys already found some time to check this out? Thanks!

**Comment by IlyaZha** [comment]
Your contribution has been accepted, and we truly appreciate the time and effort you invested in it.

**Comment by hostep** [comment]
Super, thanks! 🙂

**Comment by hostep** [comment]
Hi @IlyaZha: when do you plan to release a new version with this fix included? Thanks!

**Comment by pecinaon** [comment]
Hello,
we are still testing one new feature for batch processing of notifications, which should speed up the auctioning of the stores of users who also use the Koongo service.

I think we should release it by the end of the week. 

Thanks for your help and have a nice day Andrew.

**Pull request merged**
